ci: Other tests writer

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,6 +16,10 @@ jobs:
   test:
     name: Build and Test
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      issues: read
+      checks: write
     steps:
       - uses: actions/checkout@v3
       - name: Setup .NET Core SDK
@@ -35,11 +39,18 @@ jobs:
         run: dotnet build --configuration Release --no-restore
       - name: Run tests with code coverage
         run: dotnet test --configuration Release --no-restore --collect:"XPlat Code Coverage" --no-build --verbosity minimal --logger trx
-      - name: Test Report
-        uses: dorny/test-reporter@v1.6.0
-        if: success() || failure()            # run this step even if previous step failed
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1.6.0
+      #   if: success() || failure()            # run this step even if previous step failed
+      #   with:
+      #     name: Test results           # Name of the check run which will be created
+      #     path: tests/**/TestResults/*.trx    # Path to test results
+      #     reporter: dotnet-trx                # Format of test results
+      #     list-tests: failed                  # Only list failed tests vs all tests
+      - name: Publish Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        if: always()
         with:
-          name: Test results           # Name of the check run which will be created
-          path: tests/**/TestResults/*.trx    # Path to test results
-          reporter: dotnet-trx                # Format of test results
-          list-tests: failed                  # Only list failed tests vs all tests
+          files: |
+            **/*.trx
+          comment_mode: off
